### ISSUE TITLE
Feature Request: keep current position when reload file

### ISSUE THREAD

**Issue by hiberabyss** [Shougo/vinarise.vim#31]
Currently, when reload a binary file, the cursor will be put at the start of the file; could the cursor position be kept when reload file?

This plugin is very useful, thanks for your work!

**Comment by Shougo** [comment]
> Currently, when reload a binary file, the cursor will be put at the start of the file; could the cursor position be kept when reload file?

Vinarise must save the position in the file.
I don't want to create it.

**Comment by Shougo** [comment]
What is the reload means?

**Comment by hiberabyss** [comment]
Reload with `<Plug>(vinarise_reload)` when binary file is changed.

**Comment by Shougo** [comment]
OK.  I will implement it.

**Comment by hiberabyss** [comment]
Great to hear it!

Thanks!

**Comment by Shougo** [comment]
It is not so hard.

**Comment by Shougo** [comment]
Implemented.

**Comment by hiberabyss** [comment]
It works, thanks :)
