### ISSUE TITLE
After <q> Hide vinarise buffer , how can i return Vinarise buffer ?

### ISSUE THREAD

**Issue by Ihexon** [Shougo/vinarise.vim#33]
Hi
After <q> Hide vinarise buffer , how can i return that Vinarise buffer ?
I read help document carefully, but can find anything help.
I guess I need to 
: Vinarise 
to reopen binary in Vinarise hex mod after press <q> ??

**Comment by Shougo** [comment]
You can use `#` to return.

**Comment by Ihexon** [comment]
Thank you !
