### ISSUE TITLE
Auto detection doesn't work

### ISSUE THREAD

**Issue by Jorengarenar** [Shougo/vinarise.vim#35]
I've added `let g:vinarise_enable_auto_detect  = 1` to my `.vimrc`. Then I tried opening file with and without `.bin` extension and with passing and not passing `-b` flag to Vim.

I every case Vinarise has never opened automatically.

Although `g:vinarise_detect_large_file_size` works properly.

P.S. Is there a possibility to add a variable to change the number of bytes displayed in one line?

**Comment by Shougo** [comment]
vinarise auto detect pattern is:

```
[\x01-\x08\x10-\x1a\x1c-\x1f]\{5,}
```

This pattern is not perfect.

If you upload the binary file, I will test it though.
If not, I will ignore your issue.

> P.S. Is there a possibility to add a variable to change the number of bytes displayed in one line?

No.  It is not supported.

**Comment by Jorengarenar** [comment]
I was testing it against just the C++ [Hello World!](https://github.com/Jorengarenar/test/blob/master/test)

**Comment by Shougo** [comment]
OK.  I will test it later.
