### ISSUE TITLE
Error detected while processing function <SNR>25_browse_check

### ISSUE THREAD

**Issue by tex** [Shougo/vinarise.vim#39]
Hi, after last update, this error is shown when opening some files (I have let g:vinarise_enable_auto_detect = 1):

Error detected while processing function <SNR>25_browse_check:                                                                          
line   21:                                                                                                                              
E691: Can only compare List with List                                                                                                   
E15: Invalid expression: head =~# '[\x00-\x08\x10-\x1a\x1c-\x1f]\{2,}' || (g:vinarise_detect_large_file_size > 0 &&        getfsize(path
) > g:vinarise_detect_large_file_size)

**Comment by Shougo** [comment]
Fixed
